# Generated by Django 3.1.1 on 2020-09-22 13:27

import Account.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Account.user')),
                ('branch', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
            bases=('Account.user',),
            managers=[
                ('objects', Account.managers.StudentManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Account.user')),
                ('subject', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
            bases=('Account.user',),
            managers=[
                ('objects', Account.managers.TeacherManager()),
            ],
        ),
    ]
