# Generated by Django 3.1.1 on 2021-04-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0007_auto_20190111_0542'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('Account', '0003_student_sap_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
